### ISSUE TITLE
3sdk command to drive the user experience

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-ng#135]
child of #129 
Port 3sdk to jsng
## user experience

- [x] nice shell
- [x] commands for threebot
- [x] expert mode
  - container
  - code on host
- [x] bundle in pyinstaller
- [ ] update command
 
## Update procedure:
the binary itself could selfupdate just like in jsx
We need me make sure the 'secureconfig' is always stored on the host.
During upgrade we check if there is a new 'image' available and recreated the container with the new image.

**Comment by grimpy** [comment]
this needs better specs for people to work on this.

Will this work like the existing 3sdk aka manage docker containers for you?
Sync code?

**Comment by alichaddad** [comment]
Regarding the update procedure the release process needs to be finalized before it can be deemed to be done.

Idea is that jsng module version will be the same as both the release tag as well the docker images tags. So the binary can check what its current version is and update the sdk and images accordingly.
