### ISSUE TITLE
nettools/netconfig

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-ng#147]
- review
- import
- document

**Comment by BolaNasr** [comment]
Netconfig : https://github.com/threefoldtech/js-sdk/commit/a72ffa87ada507931ebc543c1d59b91c31c3e1ee

nettools : https://github.com/threefoldtech/js-ng/blob/development/jumpscale/sals/nettools/__init__.py

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
