### ISSUE TITLE
zdb client

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-ng#154]
- import
- review
- document

**Comment by RafyAmgadBenjamin** [comment]
* I have done the basic structure 
* working on zdbclient
### commit
https://github.com/js-next/js-ng/commit/af7e17652c3b8c3a1d9e466469698e09e5a804c0

**Comment by RafyAmgadBenjamin** [comment]
* I have imported admin client and user client 
* I have imported user and sequential from zdb store
* working on designing them to work in the right way in the js-ng factory

**Comment by RafyAmgadBenjamin** [comment]
Ideas for enhancing the design

- two classes are empty, we can remove them and handle the only function there in the ZDBClientBase

![image](https://user-images.githubusercontent.com/46320202/78891076-1a51a580-7a67-11ea-9289-5c66d2c31300.png)
 
- we can abstract sequential and user classes but I am afraid that It gets more complex as we are adding more classes

**Comment by RafyAmgadBenjamin** [comment]
all the code now imported  on ```development_zdbclient``` branch

**Comment by xmonader** [comment]
not sure if this would ever be needed with the usage of bcdb backend? to review in next
