### ISSUE TITLE
digital ocean client

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-ng#156]
digital ocean client from jsx

- import
- review
- document

e.g
```
do1 = j.client.do.new("do1")
p1 = do1.projects.new....
d1 = p1.droplets.new...
d1.start()

do operates on projects and each project operates on droplets...

do1.get_project
do1.get_droplet(project_name, ....)



```

**Comment by RafyAmgadBenjamin** [comment]
I have imported the code, reviewed it and fixed some issues there 

commit
https://github.com/js-next/js-ng/commit/6cb888c31d14d6a300746ab13d6c6a8306c58bdc

**Comment by RafyAmgadBenjamin** [comment]
How 
* you need to create sshkey 
* add the sshkey to you digital ocean client 
* get your digital ocean token 
### working example
```python 
# script to get sshkey client with the public key

ssh = j.clients.sshkey.get(name= "test")
ssh.private_key_path = "/home/rafy/.ssh/id_rsa" 
ssh.load_from_file_system()  

# script for digital ocean 
dg = j.clients.digitalocean.get("testDG")
dg.token_ = "your token"
dg.sshkey_set_default(ssh)
```

**Comment by RafyAmgadBenjamin** [comment]
still working on documentation

**Comment by RafyAmgadBenjamin** [comment]
working on refactoring the structure, but I am blocked on a feature will be implemented to access the parent object from the overridden factory

**Comment by RafyAmgadBenjamin** [comment]
* I have overridden new and  list_all methods to work in the new structure

issues in the new structure:
- list_all will list the object with the instance name while I should expect to see the actual name that has been written
- get will work only with the instance name 
     - I have tried to override the get implementation but it leads me to recursion as while listing the object it leads me to new method and new method  leads me to get method and so on
     - I have tried to override the get by calling the super but giving it the validated name but it leads to that if the instance is not there it will get it successfully but if it is not there it will call new which will also validate the name again and that leads that the name changed while creating the instance 
 
### Proposed solutions
- depend on the `instance_name` in get method and list but this will be nonsense as the one who will use it will create new instance for example with name `test test` and while getting it or listing it, it will be `_test_test`
- make a validation function that checks all cases and make sure if the name provided is valid and never validate if it is already validated but I think this solution may cause some edge cases so it must be tested extensive (I am not sure if it is a clean solution that's why I did not go for it)
- find a  way to list objects without using list_all to prevent the recursion

**Comment by RafyAmgadBenjamin** [comment]
I have refactored but still working on documentation 

commits
https://github.com/js-next/js-ng/commit/295e7fc5564428180669b418fc53ddb076f06192
https://github.com/js-next/js-ng/commit/015c6b9ccd8a16204e9bbed0bf2117900c6cbdd6
https://github.com/js-next/js-ng/commit/0cf8998e79f4cec3e60b48f3d68efd8aa49a87e1
https://github.com/js-next/js-ng/commit/94b0c9329e6bed116dffbae353abdbaec218c33c
https://github.com/js-next/js-ng/commit/7fbcd7afce4a440568c8aa0076eda2ccb55f867b

**Comment by RafyAmgadBenjamin** [comment]
### Refactor some methods names
#### commit
https://github.com/js-next/js-ng/commit/c4f6308fb2473f939f89acb681555c033cd649e4

### Documenting the client
##### commit
https://github.com/js-next/js-ng/commit/93e6eb5853f7df306dcd4adfb011333755c990e9

**Comment by Dina-Abd-Elrahman** [comment]
- project creation and deletion working fine. But, creating a droplet working only if we set the project as a default, and we don't pass the `project_name` as an argument. If we pass the `project_name` as an argument it raises an error. 

![error](https://user-images.githubusercontent.com/21218053/85950889-d2546780-b95f-11ea-9ab4-b1ad3f5d1619.png)
![error](https://user-images.githubusercontent.com/21218053/85950897-e13b1a00-b95f-11ea-8b9c-d9094349e2ab.png)

**Comment by Dina-Abd-Elrahman** [comment]
*steps to reproduce*

- dg = j.clients.digitalocean.get("testDG")
- dg.token_ = "TOKEN"
- dg.set_default_sshkey(ssh)
- droplet = dg.droplets.new("test_droplet_dg")
- droplet.set_digital_ocean_name("droplet")
- droplet.deploy(sshkey="Dina_Abd_ElRahman", region='Amsterdam 3', image='ubuntu 18.04', size_slug='s-1vcpu-2gb', project_name="TEST_DO")

**Comment by RafyAmgadBenjamin** [comment]
#### Fixing bug and update the docs
https://github.com/threefoldtech/js-sdk/commit/3735d6830c7e528c7dde04321b4cc25c46681070
#### PR
https://github.com/threefoldtech/js-sdk/pull/130

**Comment by Dina-Abd-Elrahman** [comment]
- DO client is working fine, we can close the issue  now.
