### ISSUE TITLE
encryption facilities from jsx

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-ng#164]
check `j.me` and `j.identities` from unstable_identity branch

**Comment by xmonader** [comment]
lacking documnetation

**Comment by RafyAmgadBenjamin** [comment]
I am verifying this

**Comment by RafyAmgadBenjamin** [comment]
verified 
#### For Identity
```
me = j.core.identity.me
me.tname
```
![image](https://user-images.githubusercontent.com/46320202/86233891-6445b580-bb96-11ea-9235-8b45e3cc2591.png)

#### For encryption
![image](https://user-images.githubusercontent.com/46320202/86234011-99ea9e80-bb96-11ea-8cc2-f4d9d73e5ef4.png)
![image](https://user-images.githubusercontent.com/46320202/86234067-ae2e9b80-bb96-11ea-99a3-3f7632be9bf0.png)
