### ISSUE TITLE
performance problem with accessing j object attributes

### ISSUE THREAD

**Issue by ahelsayd** [threefoldtech/js-ng#208]
![image](https://user-images.githubusercontent.com/24386820/79220768-f3bfb000-7e54-11ea-8d9b-fdc200e7d4a0.png)

![image](https://user-images.githubusercontent.com/64129/79221376-f969c580-7e55-11ea-99c6-d016e2ba71a1.png)

**Comment by xmonader** [comment]
shouldn't be the case right now, moving to next to check.

**Comment by ashraffouda** [comment]
not the case now.
