### ISSUE TITLE
Create ci with github actions

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/js-ng#210]

**Comment by RafyAmgadBenjamin** [comment]
### black-docstr pipeline
This one is crashing as black action doesn't succeed causing the whole pipeline to crash.
the pushed code must be black formatted or allow the action to format the code into a black format to make it pass 
![image](https://user-images.githubusercontent.com/46320202/85948108-302c8380-b94f-11ea-8e1b-361048b8490c.png)

### jsng-ci pipeline
This one is crashing as the tests failing to cause the whole pipeline to crash
we must make all the tests pass to allow the pipeline to work correctly 
![image](https://user-images.githubusercontent.com/46320202/85948160-91eced80-b94f-11ea-89a6-192adb9aeba4.png)

**Comment by xmonader** [comment]
to be revised in next.

**Comment by xmonader** [comment]
already implemented 🥳
