### ISSUE TITLE
prepare a 3rd backend for using bcdbreboot

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-ng#226]
prepare a 3rd backend for using bcdbreboot

new store, get, set and find.

**Comment by abom** [comment]
Added an example for authenticated python client at https://github.com/threefoldtech/dbreboot/pull/38.

Now we need to use words/mnemonic to get private keys, and also, need to have some identity management related to tf grid explorer, which we still don't have.

**Comment by xmonader** [comment]
that should be unblocked already, but to be reviewed in the next milestone
