### ISSUE TITLE
override magic methods to show better description of configuration/config manager

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-ng#261]
![Screenshot from 2020-05-31 14-05-18](https://user-images.githubusercontent.com/10658229/83351849-d46adc80-a347-11ea-9622-047c7b225db0.png)

**Comment by xmonader** [comment]
@abom  what is the status of the nsloader? it'd be solved automatically with it?

**Comment by abom** [comment]
nsloader is ready, but I don't think it resolve this issue

I think we need a `__str__` implementation for Base and Factory/StoredFactory implementation.

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** ed5cf89649fd787ea34581a5ff2f1344e772e4a4 , **Branch** development

![Screenshot from 2020-09-07 14-41-44](https://user-images.githubusercontent.com/21218053/92388910-540f0100-f118-11ea-9962-dbb7d1ce2939.png)
