### ISSUE TITLE
Package manager missing features

### ISSUE THREAD

**Issue by AhmedSa-mir** [threefoldtech/js-ng#275]
Package manager now has only 

- [X] List packages
- [X] Add package via path

Missing features include:

- [x] Add package via git url
- [x] Delete package
- [x] Start package
- [x] Stop package

**Comment by AhmedSa-mir** [comment]
https://github.com/js-next/js-sdk/issues/2

**Comment by waleedhammam** [comment]
if you delete a corrupted package or doesn't exist, it'll fail

![Screenshot from 2020-06-08 10-44-41](https://user-images.githubusercontent.com/10658229/84010584-25e12000-a975-11ea-9573-473685dce0fb.png)

**Comment by RafyAmgadBenjamin** [comment]
i am verifying this

**Comment by RafyAmgadBenjamin** [comment]
#### List all the package
```
JS-NG> j.servers.threebot.default.packages.list_all()                     
dict_keys(['auth', 'chatflows', 'admin', 'admin_old', 'weblibs', 'tfgrid_solutions'])                             
```
#### Add package through path 
```
JS-NG> j.servers.threebot.default.packages.add("/home/rafy/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/farmmanagement/")
JS-NG> j.servers.threebot.default.packages.list_all()                                                  
dict_keys(['auth', 'chatflows', 'admin', 'admin_old', 'weblibs', 'tfgrid_solutions', 'farmmanagement'])
```
#### Add package through git URL

**Comment by RafyAmgadBenjamin** [comment]
### Issue  found while deleting a package 
```
JS-NG> j.servers.threebot.default.packages.delete("foo")
```
![image](https://user-images.githubusercontent.com/46320202/86592061-0698db00-bf93-11ea-92d3-cc779e796f5b.png)

#### Foo is not a default package 
the default packages are 
![image](https://user-images.githubusercontent.com/46320202/86592099-16b0ba80-bf93-11ea-83c7-cb76c20534d9.png)
