### ISSUE TITLE
import reservation chatflow from jsx

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-ng#276]
https://github.com/threefoldtech/jumpscaleX_libs/blob/development/JumpscaleLibs/sal/reservation_chatflow/reservation_chatflow.py

Reservation chatflow sal functions can be called from within a chatflow to help creating,registering, and parsing the result types to be used in the chatflow.

working on branch: https://github.com/js-next/js-ng/tree/development_threebot_reservationchatflow

- list_networks   
    - [X] import
    - [X] verify
- get_nodes
    - [X] import
    - [X] verify
- list_wallets
    - [X] import
    - [X] verify
- validate_user
    - [X] import
    - [X] verify
- check_farms
    - [X] import
    - [X] verify
- _distribute_nodes
    - [X] import
    - [X] verify
- filter_nodes
    - [X] import
    - [X] verify
- validate_node
    - [X] import
    - [X] verify
- list_delegate_domains
    - [X] import
    - [X] verify
- check_solution_type
    - [X] import
    - [X] verify
- decrypt_reservation_metadata
    - [X] import
    - [X] verify
- get_solution_domain_delegates_info
    - [X] import
    - [X] verify
- get_solutions_explorer
    - [X] import
    - [X] verify
- get_solutions
    - [X] import
    - [X] verify
- save_reservation
    - [X] import
    - [X] verify
- get_solution_ubuntu_info
    - [X] import
    - [X] verify
- get_solution_exposed_info
    - [X] import
    - [X] verify
- get_solution_flist_info
    - [X] import
    - [X] verify
- get_kube_network_ip
    - [X] import
    - [X] verify
- get_currency
    - [X] import
    - [X] verify
- create_payment
    - [X] import
    - [X] verify
- get_payment_details
    - [X] import
    - [X] verify
- add_reservation_metadata
    - [X] import
    - [X] verify
- get_solution_model
    - [X] import
    - [X] verify
- cancel_solution_reservation
    - [X] import
    - [x] verify
- register_and_pay_reservation
    - [X] import
    - [x] verify
- register_reservation
    - [X] import
    - [x] verify
- get_ip_range
    - [X] import
    - [x] verify
- create_network
    - [X] import
    - [x] verify
- show_escrow_qr 
    - [X] import
    - [x] verify
- get_network
    - [X] import
    - [x] verify
- show_payments
    - [X] import
    - [x] verify
- wait_payment
    - [X] import
    - [x] verify
- _reservation_failed
    - [X] import
    - [x] verify
- wait_reservation
    - [X] import
    - [x] verify
- list_gateways
    - [X] import
    - [x] verify
- select_gateway
    - [X] import
    - [x] verify
- select_farms
    - [X] import
    - [x] verify
- select_network
    - [X] import
    - [x] verify
- get_farm_names
    - [X] import
    - [x] verify
___
- [x] Add docstrings

**Comment by waleedhammam** [comment]
with maged.

the remaining methods are

    validate_user
    _nodes_distribute
    nodes_filter
    farms_check
    farm_names_get
    nodes_get
    validate_node
    network_select
    farms_select
    ip_range_get
    network_create
    currency_get
    network_list
    solution_model_get
    reservation_metadata_add
    solution_name_add
    network_name_add
    solutions_get
    reservation_cancel_for_solution
    network_get
    delegate_domains_list
    gateway_list
    gateway_select
    gateway_get_kube_network_ip

**Comment by m-motawea** [comment]
remaining methods require a chatflow object as a paramter.
will be verified during migration of sdk chat solutions https://github.com/js-next/js-sdk/issues/4

**Comment by waleedhammam** [comment]
blocked on: https://github.com/js-next/js-sdk/issues/7
