### ISSUE TITLE
`j.clients.explorer.get("default")' gives error

### ISSUE THREAD

**Issue by AhmedSa-mir** [threefoldtech/js-ng#277]
`j.clients.explorer.get("default")` gives error when executed

![Screenshot from 2020-06-03 15-26-05](https://user-images.githubusercontent.com/18093386/83642015-958a9000-a5ae-11ea-9980-ca20f98e75f4.png)

**But** when I execute `j.clients.explorer.get_default` (this works well) and then execute `j.clients.explorer.get("default")` it works.

**Branch:** development_threebot

**Comment by AhmedSa-mir** [comment]
Should only use `j.clients.explorer.get_default()` to get default explorer client. `j.clients.explorer.get("default")` is not a correct way now.

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
