### ISSUE TITLE
executor improvements

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-ng#286]
here we list all of the problems of executor

- [ ] make it possible to pass command + arguments as list

This is to prevent getting into trouble with escaping and whitespaces in the future

**Comment by hossnys** [comment]
verified 
![Screenshot from 2020-07-06 12-43-24](https://user-images.githubusercontent.com/26298009/86585437-c3d10600-bf86-11ea-86bd-1d68543b25bc.png)
