### ISSUE TITLE
Fetch timeout causes chatflows to stuck

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-ng#312]
![Screenshot from 2020-06-11 11-29-13](https://user-images.githubusercontent.com/10658229/84369255-dc900b00-abd6-11ea-90d8-2f93a415f8e7.png)

after certain time chatflows hangs and doesn't work until you refresh

**Comment by m-motawea** [comment]
show alert in commit: https://github.com/threefoldtech/js-sdk/commit/f7334ac5032c60d8465f14af7578ff896118d8da

**Comment by waleedhammam** [comment]
Ther alert is too annoying, we should increase nginx/bottle request timeout instead
