### ISSUE TITLE
Raised exception does not create alert

### ISSUE THREAD

**Issue by AhmedSa-mir** [threefoldtech/js-ng#313]
Tried to  start a package with wrong name. Exception was raised but no alert created in alerts page.

![image](https://user-images.githubusercontent.com/18093386/84379206-b6be3280-abe5-11ea-896e-1345460880b4.png)
![image](https://user-images.githubusercontent.com/18093386/84379214-ba51b980-abe5-11ea-831b-e5d84919a644.png)

used `sys.excepthook = j.tools.errorhandler.excepthook` also does not work.

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
