### ISSUE TITLE
indexing/search for configuration

### ISSUE THREAD

**Issue by abom** [threefoldtech/js-ng#318]
Try to evaluate `whoosh` for fields/data indexing

- [x] added a generic find for config store.
- [x] enable selecting whoosh from configuration (with correct needed parameters)
- [x] implement find for factories
- [x] create whoosh schema from base types (see if it can be created in runtime).
- [x] implement add/list/delete with `instance_name_` as a mandatory unique whoosh field.
- [x] implement find using whoosh queries
- [x] Explicit saving -not auto-save anymore, and it's much faster :laughing:-
- [x] `find_many` should return the new cursor if any and a generator for results (also `store.find`).
- [x] More documentation for stores and how to use them (including whoosh store).
- [x] Document `find_many` and it's relation to current configured store.

For later
~- [ ] handle schema updates (maybe with migrations)~
~- [ ] caching for factories (as a layer on top-of data stores, need to discuss if we will require e.g. redis).~

**Comment by abom** [comment]
After some investigation, there're two ways to implement this, either we support indexing for any base type used with stored factories, or we add `whoosh` as another storage type, in both cases, we need to consider the following:

* Mapping from our configuration fields to `whoosh` fields.
* Data consistency via migration/versioning (`whoosh` schema can be modified).

I'm still trying multi-process read/writes (using AsyncWriter).

**Comment by abom** [comment]
It seems like `AsyncWriter` works well with `gevent`.

Will start implement `whoosh` as store backend.

**Comment by abom** [comment]
Some tests still fail (stored factory tests).

They are mostly related to stored `None` values and `Enums`, can be checked later.

**Comment by abom** [comment]
Used `MultifieldParser` for multi-field queries:

So, it can be used with multiple fields like:

```
factory.find_man(first_name="ab", rating=1)
```

**Comment by abom** [comment]
Also, Float numeric fields are not working in whoosh, related issue:

https://bitbucket.org/mchaput/whoosh/issues/448/whoosh-numeric-float-fields

**Comment by abom** [comment]
This code had an issue when saving:

```
from jumpscale.core.base import Base, fields, StoredFactory 
class Model(Base): 
    run_id = fields.String() 
    status = fields.String(required=True) 
    result = fields.List(field=fields.Typed(dict))
m = StoredFactory(Model)
o = m.new("test", status="error", run_id="12", result=[{"name": "test2", "type": "log", "content": "this is a test"}])
```


![photo_2020-06-22_10-27-47](https://user-images.githubusercontent.com/511438/85265757-08cb4780-b473-11ea-906b-68ac54f990da.jpg)

**Comment by abom** [comment]
Handled `Enum` with different types dynamically, now we only have the `float` issue.

Another link from github:

https://github.com/whoosh-community/whoosh/issues/448.

**Comment by abom** [comment]
Also, the problem mentioned [here](https://github.com/threefoldtech/js-ng/issues/318#issuecomment-647367535) is fixed.

**Comment by AhmedHanafy725** [comment]
on commit: https://github.com/threefoldtech/js-ng/commit/e63cef73a0556e3c8915f07c499e74336b470421

objects returned from `find_many` are not exact matching for what is searched for.

![image](https://user-images.githubusercontent.com/41957921/85547263-03f6c700-b61e-11ea-8cdc-458c4e2e260b.png)

**Comment by abom** [comment]
The problem mentioned [here](https://github.com/threefoldtech/js-ng/issues/318#issuecomment-648762738) should be fixed by this commit https://github.com/threefoldtech/js-ng/pull/322/commits/5240483ab27405f107f8a49a19e9fca517200fc7.

**Comment by abom** [comment]
Now the store and generic search are ready, also added docs at https://github.com/threefoldtech/js-ng/blob/9c391338ed6c840ce2e941fa1cc6ea3ca3ab59be/docs/wiki/stores.md#always-reload.

**Comment by RafyAmgadBenjamin** [comment]
I am verifying it

**Comment by ashraffouda** [comment]
verifying
