### ISSUE TITLE
core docs review

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-ng#326]
- [x] configuration mgmt review, advanced fields, secret fields
- [x] jinja 
- [x] core.config 
- [x] container mgmt @ashraffouda 
- [x] time/arrow examples
- [x] codeloader
- [x] events/triggers
- [x] current loading
- [x] mybinder @RafyAmgadBenjamin 
- [x] schemac
- [x] current repo setup (githubworkflow, docker images)
- [x] dirs 
- [x] cookiecutter
- [x] tmux
- [x] startupcmd 
- [x] platform info 
- [x] wiki update

**Comment by xmonader** [comment]
- schemac: 6488132818cfa91ec8320a5660457e93ccd7d802

**Comment by xmonader** [comment]
- core.config d34f54fb100cac4b3e31d38a4147ce2111716c03

**Comment by xmonader** [comment]
- core.dirs 80ae52740f71b4bb4051d0fc247bf0246bc4a186

**Comment by xmonader** [comment]
- cookiecutter docs: a63f9b2818f4ad20c8eee62453e3cdbfe1c491c6

**Comment by xmonader** [comment]
wiki upgrades in f60cb6f700acd225e95be698f23defd6c227a1f9

**Comment by xmonader** [comment]
platforminfo: acd04329cf7fc61822be241a89cd1ae9fb0a263a

**Comment by xmonader** [comment]
jinja2: 5d73bd310213f4c2c328170bc2ccc0a3fabecdaa

**Comment by xmonader** [comment]
codeloader: c39cef5440b7a6a626dcc9f362be5a200e48faf3

**Comment by RafyAmgadBenjamin** [comment]
mybinder https://github.com/threefoldtech/js-ng/commit/54d4183bbe157bc46296f8400306704507d6f3b2

**Comment by xmonader** [comment]
rest for loading, configmgmt, triggers seems to be in ok state.

**Comment by RafyAmgadBenjamin** [comment]
I am verifying this
