### ISSUE TITLE
update and review ssh relevant features and docs

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-ng#344]
- [x] sshkey
- [x] sshclient
- [x] jsync

**Comment by RafyAmgadBenjamin** [comment]
I have checked and update some docs 
### commits
#### sshkey
 https://github.com/threefoldtech/js-ng/commit/5f2e24df2d8690dbde178783b9263081d638fb13
#### sshclient
https://github.com/threefoldtech/js-ng/commit/cf468b161e5bc9c6e7f8bbef4edcf66dfde4a008
#### jsync
https://github.com/threefoldtech/js-ng/commit/b428e4dc5c06dfc534348f8cfd7aad3601c67bea

**Comment by Pishoy** [comment]
not sure if that should work to show command docs or it is changed, plz advice 

![image](https://user-images.githubusercontent.com/21987477/86768445-e2e69b00-c04d-11ea-96f3-ad89145c8902.png)

**Comment by xmonader** [comment]
@Pishoy please follow the docs of sshclient and jsync tools in the modules https://github.com/threefoldtech/js-ng/blob/development/jumpscale/clients/sshclient/sshclient.py
