### ISSUE TITLE
jsng --help raises error

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-ng#345]
first `jsng --help` doesn't exist and when it tries to log the error in redis

![image](https://user-images.githubusercontent.com/64129/85226464-e20c0300-b3d7-11ea-9d1e-996f03f49f11.png)

**Comment by ahelsayd** [comment]
the error from redis is fixed, but jsng doesn't have help option

**Comment by Pishoy** [comment]
verified but not sure if we can enhance message like `command not found` or something else instead error 

![image](https://user-images.githubusercontent.com/21987477/85943039-b9cb5980-b92d-11ea-98c7-953e937b71ad.png)

**Comment by OmarElawady** [comment]
I used `click` for jsng like jsctl command which has `--help` message support by default.

**Comment by xmonader** [comment]
verified

```
~> jsng --help  
Usage: jsng [OPTIONS] [COMMAND]

  Executes the passed command and initiates a jsng shell if no command is
  passed.

Options:
  --help  Show this message and exit.
~>  jsng "j.data.idgenerator.chars(5)" 
ZPQHK
```
