### ISSUE TITLE
Add field name to error message when validating

### ISSUE THREAD

**Issue by alichaddad** [threefoldtech/js-ng#356]
It would be nice if we can add field name to the error message when validation for that field fails.
At the moment we rely on the stacktrace we get from `jsng` shell.

**Comment by abom** [comment]
Still needs verification.

**Comment by OmarElawady** [comment]
A new method called validate_with_name is added to the class Field that calls the original validate method and prepends the field name to the error message if an exception was thrown.

**Comment by RafyAmgadBenjamin** [comment]
I will verify it

**Comment by RafyAmgadBenjamin** [comment]
#### verified
#### commit_id 4321aea8b20e965328134f7f82fe13e793a2090d
```
JS-NG> t = j.clients.sshclient.new("test_ssh")                                                                                                                                                                     
JS-NG> t.port                                                                                                                                                                                                      
22
JS-NG> t.port = "test"    
```

![image](https://user-images.githubusercontent.com/46320202/87420565-cf02e200-c5d5-11ea-8611-08dda31a2c02.png)
