### ISSUE TITLE
can't have identity separate from the 3bot connect

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-ng#358]
I want to try to have an identity separate from the 3bot wallet app, where it generates the words for me e.g testing purposes instead of having to use the words from 3bot connect.
(not to be used from the portal anyhow)

**Comment by xmonader** [comment]
@grimpy is that possible or the explorer will complain if i'm not using a 3bot connect valid user with its words ?

**Comment by grimpy** [comment]
during authentication in the portal we don't do any checks against the jumpsclale identities those things are loose from eachother.

The only reason we have required this in the past is for users to not get themselves in trouble by having to store words for the 3bot connect app and the identity on the grid.
Ideally they would be 1 system in the end.

Bare in my if we generate words and the user does not store them properly he will loose access to his identity and won't be able to control his reservation any longer (or manage his farms) for this reason we have put the restriction in place

**Comment by grimpy** [comment]
For experts or other automation we can do it manually.
It's also documented at https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/identity.md
![image](https://user-images.githubusercontent.com/143869/86770660-4cb47400-c051-11ea-944f-45904135af0e.png)
