### ISSUE TITLE
j.tools.console.printcolors should accept kwargs for formatting strings

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-ng#364]
currently it can only used with color formatters, but renders useful when wanting to use with f-strings or .format

**Comment by m-motawea** [comment]
for usage with f-strings or with .format we can escape colors using `{{RED}}`
```python
JS-NG> j.tools.console.printcolors(f"{{RED}}Hello world")                                                
Hello world
JS-NG> j.tools.console.printcolors("{{RED}}Hello {}".format("world"))                                    
Hello world
JS-NG>
```

![image](https://user-images.githubusercontent.com/32568986/85546330-115f8180-b61d-11ea-9098-117b29de89cb.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
