### ISSUE TITLE
startup command opens a new window for the same command that was stopped and started again

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-ng#365]
startup command opens a new window for the same `command` that was stopped and started again,  the correct behavior is to write over the same pane by name...

![image](https://user-images.githubusercontent.com/64129/85538690-6c8d7600-b615-11ea-9194-b05ce2d8c955.png)

**Comment by BolaNasr** [comment]
This issue happend when :
1- start server
2- close jsng
3- open jsng
4- stop server
5- start server again

**Comment by BolaNasr** [comment]
Fixed: https://github.com/threefoldtech/js-ng/commit/d382aadb764663e220470988805b468d4e9fe89f

**Comment by waleedhammam** [comment]
verified 
![Screenshot from 2020-06-24 14-50-10](https://user-images.githubusercontent.com/10658229/85559451-05c68780-b62a-11ea-88d0-5468ad2049cd.png)
