### ISSUE TITLE
Can't find the actor loaded in Gedis client

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-ng#374]
Can't find the registered actor in the actors list although it is loaded and I can execute the methods 

t = j.servers.gedis.get("test")
t.start()
gedis = j.clients.gedis.get("local")
gedis.register_actor("greeter", "/home/rafy/sandbox/code/github/threefoldtech/js-ng/jumpscale/servers/gedis/example_actor.py")
gedis.execute("greeter","add_two_ints",2,3) 

but if you checked the list
![image](https://user-images.githubusercontent.com/46320202/85722734-e0518080-b6f2-11ea-990f-980a522e5147.png)

**Comment by xmonader** [comment]
can you invoke
`gedis.reload()` after registering the new actor? and see if it fixes it for you.

**Comment by RafyAmgadBenjamin** [comment]
It worked and after discussing this with @ahelsayd, we have concluded that want the client to be manually reloaded after adding a new actor.
