### ISSUE TITLE
Allow fetching objects of config manager from multi process

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-ng#378]
### Steps
1- Two` jsng` shells should be available.
2- In the first shell create model and and object from this model.
```python
from jumpscale.core.base import Base, fields, StoredFactory 
class Model(Base): 
    run_id = fields.String() 
    status = fields.String(required=True) 
    result = fields.List(field=fields.Typed(dict))
m = StoredFactory(Model)
o = m.new("test", status="error", run_id="12", result=[])
o.save()
```
3- In the second shell get the this object and update it.
```python
from jumpscale.core.base import Base, fields, StoredFactory 
class Model(Base): 
    run_id = fields.String() 
    status = fields.String(required=True) 
    result = fields.List(field=fields.Typed(dict))
m = StoredFactory(Model)
o = m.find("test")
o.result = [{"name": "test"}]
o.save()
```
4- Back to the first shell and get this object again.
```python
o = m.find("test")
o.result
```

### Expected Result
Find the result field updated.

### Actual Result
result field is empty.
```python
[]
```

**Comment by abom** [comment]
Added in https://github.com/threefoldtech/js-ng/pull/322/commits/5a0a1dc399b4247c22efe76bef77e9b83118da72.

It can be enabled in the config file, just set `always_reload` to `True` in `factory` section.

**Comment by AhmedHanafy725** [comment]
**Verified**

![image](https://user-images.githubusercontent.com/41957921/86034289-993cf580-ba3a-11ea-861c-72d6d3b42a7d.png)
