### ISSUE TITLE
add docs string for remote executor

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/js-ng#380]
the remote executor has not a proper docs 

![image](https://user-images.githubusercontent.com/21987477/86006599-81ec1100-ba16-11ea-849a-881b8d4d8ac3.png)

**Comment by RafyAmgadBenjamin** [comment]
fixed
### Branch
`development_executor_docstring`
![image](https://user-images.githubusercontent.com/46320202/105633556-ef073e00-5e61-11eb-902d-faa622482909.png)

**Comment by RafyAmgadBenjamin** [comment]
Add docsting to `RemoteExecutor`

### Branch 
`development_executor_docstring`
### PR
https://github.com/threefoldtech/js-ng/pull/552

**Comment by MElborolossy** [comment]
Verified
commit e3046bd6244092e41e5610814c5cf30f5d335676
![image](https://user-images.githubusercontent.com/11272864/108868562-03745d00-75ff-11eb-8493-00d696d49fc7.png)
