### ISSUE TITLE
jsctl config: handle nested keys

### ISSUE THREAD

**Issue by abom** [threefoldtech/js-ng#390]
We need to handle nested keys with `jcstl config`, maybe dot-separated

For example, we cannot set the value of the hostname of the redis store directly:

```
[stores]

[stores.redis]
hostname = "localhost"
port = 6379
```

It would be better to do it like e.g. poetry config:

```
jsctl config get stores.redis.hostname
```

```
jsctl config update stores.redis.hostname 172.17.0.2
```

What needed to be done:

- [x] support nesed keys in get/set of core.config module
- [x] prohibit updating non-existent keys
- [x] parse the value arguement using toml decoder and fallback to string when an error occurs 
- [x] ensure type compatibility between old value and updated value
- [x] change the following name/value options to arguments

```python
@config.command()
@click.option("--name")
def get(name):
    value = get_config()[name]
    click.echo(format_config_parameter(name, value))


@config.command()
@click.option("--name")
@click.option("--value")
def set....
```

**Comment by abom** [comment]
still needs verification

**Comment by alichaddad** [comment]
Verifying
