### ISSUE TITLE
schemac: make sure schema parser and jsng plugin are in sync

### ISSUE THREAD

**Issue by abom** [threefoldtech/js-ng#403]
Or do it in a different way.

schemac jsng plugin:

https://github.com/threefoldtech/js-ng/blob/dbd2c9f94b920fd0535e3bf9f6114d0a2a2ed3e8/jumpscale/tools/schemac/plugins/jsng.py#L7-L32

j.data.types:

https://github.com/threefoldtech/js-ng/blob/dbd2c9f94b920fd0535e3bf9f6114d0a2a2ed3e8/jumpscale/data/types/types.py#L219-L238

Maybe we can maintain the list of type names in a single place, and map them in schemac (not the other way around).

**Comment by xmonader** [comment]
the types.py should get removed, we were using that for property parsing in j.data.schema, but now it's sole purpose to provide this mapping.

**Comment by xmonader** [comment]
schemac to be removed and all of the jsx types
