### ISSUE TITLE
Existing solution doesn't show up in the solutions pages

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/js-ng#408]
I've started the threebot server and click on the solution tab.
I was expecting to find all the solutions that are live on the grid also presented in here, but I found nothing.

The all reservations tab is also empty.

Is there anything special to be done to load all solutions from the explorer ?

**Comment by dmahmouali** [comment]
should fix after merge PR: https://github.com/threefoldtech/js-sdk/pull/210

**Comment by BolaNasr** [comment]
Verified
