### ISSUE TITLE
document logs and alerts flow

### ISSUE THREAD

**Issue by abom** [threefoldtech/js-ng#412]
document 
- [x] [logs](https://github.com/threefoldtech/js-ng/blob/development/docs/wiki/logging.md) 
- [x] alerts

**Comment by ahelsayd** [comment]
logging is documented here https://github.com/threefoldtech/js-ng/blob/development/docs/wiki/logging.md

**Comment by rkhamis** [comment]
handed over to ghanem.

**Comment by xmonader** [comment]
https://github.com/threefoldtech/js-ng/blob/development/docs/wiki/alerts.md
https://github.com/threefoldtech/js-ng/blob/development/docs/wiki/logging.md

**Comment by hossnys** [comment]
verified 

logs : 

![Screenshot from 2020-08-26 13-39-58](https://user-images.githubusercontent.com/26298009/91298961-30a39800-e7a1-11ea-99d2-cd68e450f7e4.png)

![Screenshot from 2020-08-26 13-39-10](https://user-images.githubusercontent.com/26298009/91298954-2ed9d480-e7a1-11ea-9b2b-b0be26645f24.png)


Alerts :

![Screenshot from 2020-08-26 13-36-23](https://user-images.githubusercontent.com/26298009/91299016-46b15880-e7a1-11ea-8665-7e3d290a629c.png)

![Screenshot from 2020-08-26 13-36-04](https://user-images.githubusercontent.com/26298009/91299013-45802b80-e7a1-11ea-8614-a5a01ceb51a9.png)

![Screenshot from 2020-08-26 13-36-58](https://user-images.githubusercontent.com/26298009/91299017-4749ef00-e7a1-11ea-9963-0153dfe258d8.png)
