### ISSUE TITLE
Test coverage for jsng

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-ng#427]
- Create automation test for all the following modules.
- Some of them has tests already, please check the coverage, and complete it if needed.

### core
  - [x] base (high priority)
    - [x] [factory](https://github.com/threefoldtech/js-ng/blob/development/tests/core/base/test_factory.py) (already covered)
    - [x] [fields](https://github.com/threefoldtech/js-ng/blob/development/tests/core/base/test_field.py) (already covered)
    - [x] [stored factory](https://github.com/threefoldtech/js-ng/blob/development/tests/core/base/test_stored_factory.py) (modified to work with all stores)
    - [x] filesystem store (already covered in stored factory)
    - [x] [redis store](https://github.com/threefoldtech/js-ng/pull/445)
    - [x] [whoosh store](https://github.com/threefoldtech/js-ng/blob/development/tests/core/base/test_store_whoosh.py) (already covered)
  - [x] [config](https://github.com/threefoldtech/js-ng/pull/445)
  - [x] [events](https://github.com/threefoldtech/js-ng/blob/development/tests/core/events/test_events.py) (already covered)
  - [x] [executors](https://github.com/threefoldtech/js-ng/tree/development/tests/core/executors) (already covered)
  - [x] [logging](https://github.com/threefoldtech/js-ng/pull/448) (one test added)

### data
  - [ ] bcdb (low prio)
  - [ ] encryption
  - [ ] hash
  - [ ] idgenerator
  - [ ] inifile
  - [ ] nacl
  - [ ] platform
  - [ ] schema 
  - [x] [serializers](https://github.com/threefoldtech/js-ng/pull/448) (json test modified)
  - [ ] tarfile
  - [ ] types

### clients
  - [x] [docker](https://github.com/threefoldtech/js-ng/pull/435)
  - [x] [gedis](https://github.com/threefoldtech/js-ng/pull/448) (added tearDown)
  - [x] git
  - [x] [redis](https://github.com/threefoldtech/js-ng/pull/445)
  - [ ] sshclient
  - [ ] sshkey
  - [ ] zdb (very low prio)

### sal
  - [ ] fs
  - [ ] hostfile
  - [ ] nettools
  - [x] [process](https://github.com/threefoldtech/js-ng/pull/440)
  - [ ] unix

### servers
  - [x] [gedis](https://github.com/threefoldtech/js-ng/blob/development/tests/servers/gedis/test_gedis.py) (already covered)
  - [ ] gedis_http (high priority)
  - [ ] openresty
  - [ ] rack

### Installation 
  - [ ] threesdk (don't test, should get removed.) 

### tools
  - [ ] alerthandler
  - [ ] codeloader
  - [ ] console
  - [ ] depsresolver
  - [ ] git
  - [ ] highlighter
  - [ ] schemac
  - [x] [startupcmd](https://github.com/threefoldtech/js-ng/blob/development/tests/tools/startupcmd/test_startupcmd.py) (already covered)
  - [ ] syncer
  - [ ] timer

**Comment by Dina-Abd-Elrahman** [comment]
- Docker client test cases

https://github.com/threefoldtech/js-ng/tree/development_testing_clients/jumpscale/clients/test

**Comment by Dina-Abd-Elrahman** [comment]
- I'm working with ZDB client.

**Comment by AhmedHanafy725** [comment]
working sal process

**Comment by Dina-Abd-Elrahman** [comment]
working on threebot server

**Comment by RafyAmgadBenjamin** [comment]
working on git client

**Comment by BolaNasr** [comment]
### FS PR : https://github.com/threefoldtech/js-ng/pull/463

**Comment by mhost39** [comment]
Git Client  https://github.com/threefoldtech/js-ng/issues/472

**Comment by xmonader** [comment]
@AhmedHanafy725 <3 thank you let's revisit the remaining items in the next sprint in a new issue as we are kicking some items out of ng completely
