### ISSUE TITLE
Release Acceptance Tests [2d]

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/js-ng#433]
This will be used to test the release candidate before the final release.

### Automated
unittests on js-ng and js-sdk in github actions
https://github.com/threefoldtech/js-ng/tree/development/tests
https://github.com/threefoldtech/js-sdk/tree/development/tests

### Manual installation
  - [x] from scratch:
    - [x] ubuntu 20.04
    - [x] ubuntu 18.04
    - [x] mac
    - [x] windows
  - [x] on a previous installation
    - [x] ubuntu
    - [x] mac
    - [x] windows

### wallets
  - [x] create
  - [x] import
  - [x] delete

### solutions & marketplace
  - [x] network
  - [x] [ubuntu](https://github.com/threefoldtech/zos/issues/889)
  - [x] kubernetes
  - [x] [minio](https://github.com/threefoldtech/js-sdk/issues/460)
  - [x] expose solutions
  - [x] [publisher](https://github.com/threefoldtech/js-sdk/issues/457), (https://github.com/threefoldtech/js-sdk/issues/459)
  - [x] threebot
  - [x] generic flist
  - [x] monitoring 
  - [ ] [domain delegation](https://github.com/threefoldtech/home/issues/875)
  - [x] [4 to 6 gateway](https://github.com/threefoldtech/js-sdk/issues/463)
  - [ ] [gitea](https://github.com/threefoldtech/home/issues/866)

### Reservations and payments:
 ~- [ ] capacity pool on testnet~
 - [x] payments on mainnet
 - [x] canceling reservations

### other functionality
 - [x] adding administrators
 - [x] removing admins from dashboard 
 - [x] switching identities
 - [x] logs
 - [x] alerts

**Comment by AhmedHanafy725** [comment]
Network and Ubuntu solutions complete to the end, but it didn't work https://github.com/threefoldtech/zos/issues/889

**Comment by AhmedHanafy725** [comment]
Add/remove admins and switching identities is working  

**alerts:**
![image](https://user-images.githubusercontent.com/41957921/89904720-901e7700-dbe9-11ea-811f-679f690b8d0c.png)

**logs:**

![image](https://user-images.githubusercontent.com/41957921/89904590-69f8d700-dbe9-11ea-9da3-22335d70ce75.png)

**Comment by AhmedHanafy725** [comment]
Creating network and ubuntu with all releases

**Ubuntu18.04**
![image](https://user-images.githubusercontent.com/41957921/89907242-b42f8780-dbec-11ea-865e-a8e1db4b2f9f.png)

**Ubuntu19.10**
![image](https://user-images.githubusercontent.com/41957921/89907137-8f3b1480-dbec-11ea-8421-62f4706d5281.png)

**Ubuntu:20.04**
![image](https://user-images.githubusercontent.com/41957921/89907881-7f700000-dbed-11ea-86e0-452753096f43.png)

### solution expose for ubuntu
**http**
![image](https://user-images.githubusercontent.com/41957921/89908623-6025a280-dbee-11ea-9da5-99b1e1f93e93.png)

**https**
![image](https://user-images.githubusercontent.com/41957921/89910869-08d50180-dbf1-11ea-9161-be1bdbc98fb1.png)

**Comment by AhmedHanafy725** [comment]
**publisher**
https://github.com/threefoldtech/js-sdk/issues/457

**kubernetes** 
![image](https://user-images.githubusercontent.com/41957921/89914225-ff4d9880-dbf4-11ea-973d-f4309b3a81cd.png)

**Comment by Dina-Abd-Elrahman** [comment]
- tested ubuntu 18.04, 20.04 ( dev, non-dev) modes.

**Comment by AhmedHanafy725** [comment]
**4 to 6 gateway** 
![image](https://user-images.githubusercontent.com/41957921/90002494-00350780-dc93-11ea-9ad1-e7d90cbf4c78.png)

**generic container** with ubuntu flist 
![image](https://user-images.githubusercontent.com/41957921/90003396-52c2f380-dc94-11ea-94b2-b3f588e70cd8.png)

**Comment by AhmedHanafy725** [comment]
**minio** 

![image](https://user-images.githubusercontent.com/41957921/90012143-2367b300-dca3-11ea-9f6e-7706010f8235.png)

**Comment by AhmedHanafy725** [comment]
**threebot**
It is working, but it has invalid certificate.

![image](https://user-images.githubusercontent.com/41957921/90013800-43e53c80-dca6-11ea-885c-4797d49c12fc.png)

**publisher**
It is deployed too, but it can't start as caddy can't generate certificate for gateway.tf https://github.com/threefoldtech/home/issues/875
![image](https://user-images.githubusercontent.com/41957921/90015451-eacad800-dca8-11ea-890a-f7fe654a7884.png)

**Comment by Dina-Abd-Elrahman** [comment]
monitoring:

![ff](https://user-images.githubusercontent.com/21218053/90016999-28306500-dcab-11ea-8c63-60bcd426ddef.png)
![ff1](https://user-images.githubusercontent.com/21218053/90017003-29619200-dcab-11ea-83f7-4a8357799cca.png)

**Comment by Dina-Abd-Elrahman** [comment]
- ubuntu tested on a previous installation.

**Comment by AhmedHanafy725** [comment]
Installation working on windows with WSL 2  with Ubuntu:20.04 
Also tried to delete it and reinstall, and it works fine.

![image](https://user-images.githubusercontent.com/41957921/90040881-cbdc3e00-dcc8-11ea-8d4a-9d4f5caa078d.png)

**Comment by AhmedHanafy725** [comment]
gitea flist has a problem 
![image](https://user-images.githubusercontent.com/41957921/90043997-46a75800-dccd-11ea-8174-155cecfe9630.png)

**Comment by AhmedHanafy725** [comment]
Installation on mac is working fine

![image](https://user-images.githubusercontent.com/41957921/90430010-fd894680-e0c6-11ea-811a-3018e3fc4f7b.png)

**Comment by AhmedHanafy725** [comment]
The remain unchecked ones are not related to jsng/js-sdk codes:
- **gitea:** has a problem in the flist
- **domain delegation:** the issue related to generate TLS certificate.
