### ISSUE TITLE
Core config features for get/set

### ISSUE THREAD

**Issue by AhmedSa-mir** [threefoldtech/js-ng#447]
### Description
In the core config file: https://github.com/threefoldtech/js-ng/blob/de3627a1c2580a89c24774149e9f7ffeac8882f6/jumpscale/core/config/config.py#L158.
We can add:
- get method with default arg
- setdefault method

**Comment by xmonader** [comment]
https://github.com/threefoldtech/js-ng/commit/c878c303837d914847c28add86a7854d6960c267
