### ISSUE TITLE
Suggest Solution for is_broken_link() in fs module

### ISSUE THREAD

**Issue by MElborolossy** [threefoldtech/js-ng#461]
## Description

Suggest solution for is_broken_link function in /sals/fs that is not implemented

### Suggested Solution
```Python
def is_broken_link(path:str, clean=False) -> bool:
    if not pathlib.Path(path).exists():
        if clean:
            pathlib.Path(path).unlink()
        return True
    else:
        return False
```

**Comment by xmonader** [comment]
please prepare a PR, also should be two separate functions one checking the existence and the other  `rm_broken_link`
