### ISSUE TITLE
sal process needs some cleanup

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-ng#467]
- Some functions are using `ps` command, and it can be done with `psutils`.
- This method shouldn't be used for single purpose, it can be generic with args for filter, sort and limit.

https://github.com/threefoldtech/js-ng/blob/3f8b76b3f852b6d0a4bab9685b0f0e9b835da6ef/jumpscale/sals/process/__init__.py#L630-L656

**Comment by xmonader** [comment]
@ashraffouda you're owning this SAL, can you please review?

**Comment by xmonader** [comment]
@ashraffouda this could be a good starting issue for @sameh-farouk please guide him through once this issue is accepted

**Comment by xmonader** [comment]
Guess this won't get merged in by tmw, I'll move to next milestone.
