### ISSUE TITLE
Exception details are "swallowed" by GedisServer

### ISSUE THREAD

**Issue by OldhamMade** [threefoldtech/js-ng#500]
### Description

The GedisServer [catches all exceptions](https://github.com/threefoldtech/js-ng/blob/master/jumpscale/servers/gedis/server.py#L230) to provide a "nice" error over the wire to the client. However, while it does this it also discards the traceback which is invaluable for diagnosing issues.

### Suggested Solutions

* Ensure that the traceback is still written to stderr.
* Add a `j.logger.error` call with traceback details.
* Provide a `error_traceback` value in the returned result JSON alongside the `error` and `error_type` values.

**Comment by xmonader** [comment]
@abom you are already working on this right?

**Comment by abom** [comment]
Yes, I already added an error log with the exception, but still didn't merge yet, as I'm trying to fix logging context (app names)

For an `error_traceback`, we don't need to expose much information to the client, what do you think @xmonader?

**Comment by abom** [comment]
Now any module can register logs under a different app name using `j.logger.register(<app name>)`
