### ISSUE TITLE
the package not passes all tests

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/js-ng#519]
### Search first

Search for similar issues first, if not complete the following template

### Description
after going through the various installation steps mentioned in the documentation on ubuntu clean installation, running the test suite results in some tests failed.

checking logs show that the package uses some software that not installed by default and not mentioned in the installation,
installing them decreased the number of failing tests.

Docker version 19.03.8, build afacb8b7f0
Redis server v=5.0.7 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=636cde3b5c7a3923
Package: tmux Version: 3.0a-2ubuntu0.2
Package: net-tools Version: 1.60+git20180626.aebd88e-1ubuntu1    (some tests used netstat that in recent Ubuntu versions  is not installed by default and considered deprecated in favor of modern ss command, to get netstat you need to install net-tools)

however, few tests still failed, with some errors.

### Version information

* OS: Ubuntu 20.04.1 LTS
* Project commit/version: js-ng 11.0b10 / cloned from default branch

poetry show
appdirs           1.4.4     A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir".
argh              0.26.2    An unobtrusive argparse wrapper with natural syntax
arrow             0.15.8    Better dates & times for Python
astroid           2.4.2     An abstract syntax tree for Python with inference support.
attrs             20.3.0    Classes Without Boilerplate
backcall          0.2.0     Specifications for callback functions passed in to an API
bcrypt            3.2.0     Modern password hashing for your software and your servers
better-exceptions 0.2.2     Pretty and helpful exceptions, automatically
black             18.9b0    The uncompromising code formatter.
bottle            0.12.19   Fast and simple WSGI-framework for small web-applications.
certifi           2020.12.5 Python package for providing Mozilla's CA Bundle.
cffi              1.14.4    Foreign Function Interface for Python calling C code.
chardet           3.0.4     Universal encoding detector for Python 2 and 3
click             7.1.2     Composable command line interface toolkit
codecov           2.1.10    Hosted coverage reports for GitHub, Bitbucket and Gitlab
colorama          0.4.4     Cross-platform colored terminal text.
coverage          5.3       Code coverage measurement for Python
cryptography      3.2.1     cryptography is a package which provides cryptographic recipes and primitives to Python developers.
decorator         4.4.2     Decorators for Humans
dill              0.3.3     serialize all of python
distro            1.5.0     Distro - an OS platform information API
docker            4.4.0     A Python library for the Docker Engine API.
docopt            0.6.2     Pythonic argument parser, that will make you smile
fabric            2.5.0     High level SSH command execution
faker             2.0.5     Faker is a Python package that generates fake data for you.
flake8            3.8.4     the modular source code checker: pep8 pyflakes and co
gevent            1.4.0     Coroutine-based network library
gitdb             4.0.5     Git Object Database
gitpython         3.1.11    Python Git Library
graphviz          0.15      Simple Python interface for Graphviz
greenlet          0.4.16    Lightweight in-process concurrent programming
hypothesis        4.57.1    A library for property-based testing
idna              2.10      Internationalized Domain Names in Applications (IDNA)
invoke            1.4.1     Pythonic task execution
ipdb              0.12.3    IPython-enabled pdb
ipython           7.16.1    IPython: Productive Interactive Computing
ipython-genutils  0.2.0     Vestigial utilities from IPython
isort             5.6.4     A Python utility / library to sort Python imports.
jedi              0.17.2    An autocompletion tool for Python that can be used for text editors.
jinja2            2.11.2    A very fast and expressive template engine.
lazy-object-proxy 1.4.3     A fast and thorough lazy object proxy.
libtmux           0.8.5     scripting library / orm for tmux
loguru            0.3.2     Python logging made (stupidly) simple
mako              1.1.3     A super-fast templating language that borrows the  best ideas from the existing templating languages.
markdown          3.3.3     Python implementation of Markdown.
markupsafe        1.1.1     Safely add untrusted strings to HTML/XML markup.
mccabe            0.6.1     McCabe checker, plugin for flake8
more-itertools    8.6.0     More routines for operating on iterables, beyond itertools
msgpack           0.6.2     MessagePack (de)serializer.
objgraph          3.5.0     Draws Python object reference graphs with graphviz
packaging         20.7      Core utilities for Python packages
parameterized     0.7.4     Parameterized testing with any Python test framework
paramiko          2.7.2     SSH2 protocol library
parso             0.7.1     A Python Parser
pathtools         0.1.2     File system general utilities
pdoc3             0.6.4     Auto-generate API documentation for Python projects.
pexpect           4.8.0     Pexpect allows easy control of interactive console applications.
pickleshare       0.7.5     Tiny 'shelve'-like database with concurrency support
pluggy            0.13.1    plugin and hook calling mechanisms for python
prompt-toolkit    2.0.10    Library for building powerful interactive command lines in Python
psutil            5.7.3     Cross-platform lib for process and system monitoring in Python.
ptpython          2.0.6     Python REPL build on top of prompt_toolkit
ptyprocess        0.6.0     Run a subprocess in a pseudo terminal
pudb              2019.2    A full-screen, console-based Python debugger
py                1.9.0     library with cross-python path, ini-parsing, io, code, log facilities
pycodestyle       2.6.0     Python style guide checker
pycparser         2.20      C parser in Python
pyflakes          2.2.0     passive checker of Python programs
pygments          2.7.2     Pygments is a syntax highlighting package written in Python.
pylint            2.6.0     python code static checker
pylzma            0.5.0     Python bindings for the LZMA library by Igor Pavlov.
pynacl            1.3.0     Python binding to the Networking and Cryptography (NaCl) library
pyparsing         2.4.7     Python parsing module
pytest            5.4.3     pytest: simple powerful testing with Python
pytest-cov        2.10.1    Pytest plugin for measuring coverage.
python-dateutil   2.8.1     Extensions to the standard Python datetime module
pytoml            0.1.21    A parser for TOML-0.4.0
pyyaml            5.3.1     YAML parser and emitter for Python
redis             3.5.3     Python client for Redis key-value store
requests          2.25.0    Python HTTP for Humans.
secretconf        0.1.2     manage your secrets and configurations easily
six               1.15.0    Python 2 and 3 compatibility utilities
smmap             3.0.4     A pure Python implementation of a sliding window memory map manager
sortedcontainers  2.3.0     Sorted Containers -- Sorted List, Sorted Dict, Sorted Set
terminaltables    3.1.0     Generate simple tables in terminals from a nested list of strings.
text-unidecode    1.3       The most basic Text::Unidecode port
toml              0.10.2    Python Library for Tom's Obvious, Minimal Language
traitlets         4.3.3     Traitlets Python config system
urllib3           1.26.2    HTTP library with thread-safe connection pooling, file post, and more.
urwid             2.1.2     A full-featured console (xterm et al.) user interface library
watchdog          0.9.0     Filesystem events monitoring
wcwidth           0.2.5     Measures the displayed width of unicode strings in a terminal
websocket-client  0.57.0    WebSocket client for Python. hybi13 is supported.
whoosh            2.7.4     Fast, pure-Python full text indexing, search, and spell checking library.
wrapt             1.12.1    Module for decorators, wrappers and monkey patching.
zipp              3.4.0     Backport of pathlib-compatible object wrapper for zip files

### Installation method
as documentation:

apt-get update
apt-get install git python3-venv python3-pip
pip3 install poetry
git clone https://github.com/js-next/js-ng.git
cd js-ng
poetry update
poetry install

### Steps to reproduce

poetry shell
make tests

### Traceback/Logs/Alerts

[log.poetry.txt](https://github.com/threefoldtech/js-ng/files/5648993/log.poetry.txt)

**Comment by xmonader** [comment]
I think it needs to follow a specific setup as defined in the github actions and run on an isolated system too

**Comment by sameh-farouk** [comment]
maybe related https://github.com/threefoldtech/js-ng/issues/540
