### ISSUE TITLE
pickle API is wrong

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-ng#532]
![image](https://user-images.githubusercontent.com/64129/103545707-9b30b700-4eaa-11eb-9954-48c212806976.png)

should be dumps/ loads 

convert to from pickle import dumps, loads

**Comment by sameh-farouk** [comment]
not sure if I'm getting that correctly. some context would be helpful.
please also review [this pull request](https://github.com/threefoldtech/js-ng/pull/538)

**Comment by abom** [comment]
This is already handled at #537.

**Comment by sameh-farouk** [comment]
> This is already handled at #537.

okay I closed my PR
