### ISSUE TITLE
jsng: add an option to disable gevent monkey patching

### ISSUE THREAD

**Issue by abom** [threefoldtech/js-ng#533]
### Description

`jsng` shell is based on `ptpython` which depends on `asyncio`, when `gevent` monkey patching is applied, the shell become too slow.

### Version information

* OS: e.g. Ubuntu 18.04
* Project commit/version: development

### Installation method

Using `poetry`

### Steps to reproduce

Open `jsng` shell and try wiriting e.g.

```
j.clients.redis.get(
```

**Comment by waleedhammam** [comment]
Verified
```
(.venv) ➜  js-ng git:(development_reduce) git --no-pager log --decorate=short -n1                 
commit 8ea8f7ac659d483a9d7e72a9c498cef78616795d (HEAD -> development_reduce, origin/development_reduce)
Merge: b6dde4d 94c049d
Author: Abdelrahman Ghanem <abom.jdev@gmail.com>
Date:   Wed Feb 10 13:10:22 2021 +0200

    Merge pull request #567 from threefoldtech/development_reduce_fix_tests
    
    Add waits to servers to start
```
![Screenshot from 2021-02-23 16-23-31](https://user-images.githubusercontent.com/10658229/108857172-7c6db780-75f3-11eb-9583-f8a81a503a9b.png)
