### ISSUE TITLE
CI build failed on ubuntu 20.4

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/js-ng#540]
### Description

in ubuntu 20.4 build failed because of 2 failed tests
FAILED tests/sals/process/test_process.py::ProcessTests::test_20_get_ports_mapping
FAILED tests/sals/process/test_process.py::ProcessTests::test_21_get_defunct_processes

### More

related to #535

**Comment by AhmedHanafy725** [comment]
For defunct processes, I think we need a wait for the process to start
For ports mapping, seems `netstat` is not installed by default on ubuntu 20.04, so we maybe can install it on the workflow `apt install -y net-tools`

**Comment by sameh-farouk** [comment]
> For defunct processes, I think we need a wait for the process to start
> For ports mapping, seems `netstat` is not installed by default on ubuntu 20.04, so we maybe can install it on the workflow `apt install -y net-tools`

confirmed. installing it in the workflow fixes the issue.
fixed in #536
