### ISSUE TITLE
etcd backend for the configmanager

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-ng#544]
- can get inspired from mongo implementation #522 
- should work against development_reduce
- etcd to be an optional dependency
- etcd store to be registered in case of etcd dependency is installed

**Comment by xmonader** [comment]
@abom please guide @MElborolossy  through this issue

**Comment by AhmedHanafy725** [comment]
**Verified**
**Branch:** development_reduce
**Commit:** 8ea8f7ac659d483a9d7e72a9c498cef78616795d

also, tests are passing on https://github.com/threefoldtech/js-ng/actions/runs/554402597
