### ISSUE TITLE
The tests are repeated when generate tests docs 

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/js-ng#551]
when using ```j.sals.testdocs.generate_tests_docs(source='tests/', target='docs/tests')``` to generate tests docs 
found test scenario repeated four and five times

**Comment by AhmedHanafy725** [comment]
This only happens with parameterized as it repeats the test while loading them

**Comment by MElborolossy** [comment]
Return to In progress
Tested in development_vdc
commit d0eea8f1482459bd507ba0bfcca889be09023f6a

![test_vdc_chatflows md (Working Tree) - JS (Workspace) - Visual Studio Code_003](https://user-images.githubusercontent.com/11272864/108872504-e8a3e780-7602-11eb-8843-e94d0d176710.png)

**Comment by xmonader** [comment]
if so, let's move it to 2.6

**Comment by MElborolossy** [comment]
Verified
The wrong result because I try it in js-sdk and js-ng not released yet.
So the old code used.
After using the write one it works fine.
