### ISSUE TITLE
Remove signal handling from Gedis server

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/js-ng#558]
### Description

In js-sdk, the SIGTERM signal is handled by the 3Bot server and then the stop method of Gedis and several other components are called. But the Gedis server also handles the signal and calls its stop method, this might cause trouble as there are no guarantees on the idempotency of this method.

**Comment by OmarElawady** [comment]
There are a couple of suggestion that was proposed to solve this issue:
1. Remove the stop handler from the rack server.
2. Remove the stop handler from the gedis server.
3. Make a global signal handler that guarantees the sequential execution of handlers to avoid concurrency issues.
Created a PR with this second option for now.

**Comment by abom** [comment]
Resolved in #559.
