### ISSUE TITLE
review documentation

### ISSUE THREAD

**Issue by abom** [threefoldtech/js-ng#615]
- flow
  - [installation](https://github.com/threefoldtech/js-ng/blob/development/docs/wiki/installation.md)
  - [testing](https://github.com/threefoldtech/js-ng/blob/development/docs/wiki/testing_contribution.md) 
  - [docs generation](https://github.com/threefoldtech/js-ng/blob/development/docs/wiki/devsetup.md#generating-docs)
   - [publishing](https://github.com/threefoldtech/js-ng#releasing--publishing)
   - [entrypoints](https://github.com/threefoldtech/js-ng/blob/development/docs/wiki/distributing_cmds.md)
- modules
   - base classes
     - [config management intro](https://github.com/threefoldtech/js-ng/blob/development/docs/wiki/configmgmt.md)
     - [base classes, fields and factories](https://github.com/threefoldtech/js-ng/blob/development/docs/wiki/baseclasses.md)
     - [stores](https://github.com/threefoldtech/js-ng/blob/development/docs/wiki/stores.md)
     - [internals](https://github.com/threefoldtech/js-ng/blob/70c05db459904a29695d419c8453b207ae75691b/docs/wiki/internals/baseclasses.md)

**Comment by xmonader** [comment]
@rawdaGastan if you find any item still unclear, please create separate issues
