### ISSUE TITLE
kosmos improvements

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-ng#69]
- docstrings pane: I've no idea why the docstrings pane shows one of my machines and not the other
- different colors for (instances, methods, properties)

**Comment by abom** [comment]
auto-completion with kosmos.

**Comment by abom** [comment]
I think this issue is already resolved? we have now auto-completion working and with colors.

**Comment by hossnys** [comment]
verified
![Screenshot from 2020-07-06 12-43-24](https://user-images.githubusercontent.com/26298009/88477865-d023ff80-cf43-11ea-9099-ef5c763e9715.png)
![Screenshot from 2020-06-22 18-48-26](https://user-images.githubusercontent.com/26298009/88477886-ff3a7100-cf43-11ea-8bfd-7b836079528d.png)
